project:
  type: website
  output-dir: docs
  resources: ["resources/dashboard"]

# Meta
description-meta: "Geospatial Analytics, Technology and Open Research (GATOR) Lab at the University of Florida"
author-meta: "Dr. Levente Juhasz"

website:
  title: "GATOR Lab @ UF"
  favicon: files/images/gator-logo-square-bg.png
  navbar:
    logo: files/images/gator-logo-square.png
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        menu:
          - text: "Our Vision & Stack"
            href: research.qmd
          - text: "Projects & Grants"
            href: projects.qmd
          - text: "Publications"
            href: publications.qmd
      - text: "People"
        menu:
          - text: "Lab Members"
            href: people.qmd
          - text: "Join the Lab" # High visibility for recruitment
            href: join.qmd
      - text: "Lab Life"
        menu:
          - text: "News & Events"
            href: posts.qmd
          - text: "Teaching"
            href: teaching.qmd
      - text: "Resources"
        menu:
          - text: "GIScience Journal Dashboard"
            href: resources/journals.qmd # Create this folder/file later
          - text: "Open Data & Tools"
            href: resources/data.qmd
    right:
      - text: "Contact"
        href: contact.qmd
      - text: "CV"
        href: files/Juhasz_UF_CV_new.pdf
      - icon: github
        href: https://github.com/orgs/gatorlab-geo/
      - icon: bluesky
        href: https://bsky.app/profile/gatorlab.bsky.social
      - icon: rss
        href: posts.xml
  page-navigation: true

  page-footer:
    left: "![](/files/images/gator-logo-square.png){width=30px} [GATOR Lab](http://www.gatorlab.io) &copy; <script>document.write(new Date().getFullYear())</script>" 
    center: "[![](/files/images/University_of_Florida_logo.svg){width=120px}](https://www.ufl.edu)<br>Adapted from [Quarto Academic Website Template](https://github.com/drganghe/quarto-academic-website-template)"
    right:
      - icon: github
        href: https://github.com/gatorlab-geo/
        target: _blank
      - text: "{{< fa brands bluesky >}}"
        href: https://bsky.app/profile/gatorlab.bsky.social
        target: _blank
      - icon: rss
        href: posts.xml
        target: _blank

  search:
    location: navbar
    type: textbox

  reader-mode: true

  draft-mode: unlinked

  repo-url: https://github.com/gatorlab-geo/gatorlab-geo.github.io
#  repo-actions: [edit, issue, source]

  open-graph: true
  image: files/images/gator-logo-square-bg.png

  twitter-card: true
#  image: files/images/gator-logo-square-bg.png
#  card-style: summary      

  site-url: "https://gatorlab.io"

  google-analytics:
    tracking-id: "G-NBL9B0EX18"  # Please delete or replace with your own tracking ID
    anonymize-ip: true 

bibliography: references.bib  # Add references.bib to the root folder to enable the bibliography function

format:
  html:
    theme: united
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    include-in-header: "files/includes/_academic.qmd"

